// Generated by CoffeeScript 1.6.2
Ram.Data = {
  loadItems: function(callback) {
    var itemsStr;

    itemsStr = localStorage['ram.items'];
    if (itemsStr) {
      return callback(JSON.parse(itemsStr));
    } else {
      return callback([
        {
          _id: '1',
          text: ['Default']
        }
      ]);
    }
  },
  saveItems: function(items, callback) {
    var itemsStr;

    itemsStr = JSON.stringify(items);
    localStorage['ram.items'] = itemsStr;
    if (callback) {
      return callback();
    }
  }
};
