// Generated by CoffeeScript 1.7.1
Ram.Data = EventDispatcher.extend({
  init: function(callback) {
    if (callback) {
      return callback(self);
    }
  },
  loadItems: function(callback) {
    var id, items, itemsById, maxLevel, parentId, parentLevel, prevId, prevLevel;
    this.items = items = [];
    parentId = [];
    parentLevel = 0;
    prevId = 0;
    prevLevel = 0;
    id = 1;
    maxLevel = 0;
    itemsById = {};
    return Ram.CacheUtils.getUrl('data/tasks.txt', function(str) {
      str.trim().split('\n').forEach(function(line, lineIndex) {
        var atIndex, i, item, level, text, _i, _ref;
        level = 0;
        while (line[level] === '\t') {
          level += 1;
        }
        level += 1;
        maxLevel = Math.max(maxLevel, level);
        text = line.trim();
        item = {};
        item.text = line.trim();
        atIndex = item.text.indexOf('@');
        if (atIndex > 0) {
          item.tags = item.text.substr(atIndex);
          item.text = item.text.substr(0, atIndex - 1);
        }
        if (item.text.substr(0, 2) === '- ') {
          item.text = item.text.substr(2);
        }
        if (item.text[item.text.length - 1] === ':') {
          item.text = item.text.substr(0, item.text.length);
        }
        item._id = id++;
        itemsById[item._id] = item;
        if (level > prevLevel) {
          if (level - prevLevel > 1) {
            level = prevLevel + 1;
          }
          parentId.push(prevId);
        } else if (level < prevLevel) {
          for (i = _i = 0, _ref = prevLevel - level; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
            parentId.pop();
          }
        }
        item.parentid = parentId[parentId.length - 1];
        prevLevel = level;
        prevId = item._id;
        return items.push(item);
      });
      return callback(items);
    });
  },
  getChildren: function(parentid) {
    return this.items.filter(function(item) {
      return item.parentid === parentid;
    });
  },
  onChange: function(change) {},
  addItem: function(item) {},
  updateItem: function(item) {},
  removeItemById: function(itemid) {},
  removeItem: function(item) {}
});
