// Generated by CoffeeScript 1.6.2
console.log('Import.importing...');

Ram.CacheUtils.getJson('stuff/hsbc-mi.json', function(items) {
  var parentid;

  parentid = '19EC603D-FE7E-4492-8EB2-C3E77D16F618';
  console.log('Import.importing Items', items.length);
  return items.forEach(function(item) {
    return item.parentid = parentid;
  });
});

/*
//@ sourceMappingURL=Import.map
*/
