// Generated by CoffeeScript 1.6.2
var AccountsController;

AccountsController = function($rootScope, $scope, $q, dataSource) {
  $scope.accounts = [
    {
      id: 'tes',
      name: 'test',
      value: 0
    }
  ];
  $scope.collapsed = true;
  $scope.selectedAccountId = localStorage['cashflow_selectedAccountId'];
  $scope.selectAccount = function(id) {
    $scope.collapsed = true;
    $scope.refreshTotal();
    if ($scope.selectedAccountId !== id) {
      $scope.selectedAccountId = id;
      localStorage['cashflow_selectedAccountId'] = $scope.selectedAccountId;
      $rootScope.$broadcast('accountChanged', id);
      return $scope.refreshTotal();
    }
  };
  $scope.onAccountClick = function(id) {
    if ($scope.collapsed) {
      return $scope.collapsed = false;
    } else {
      return $scope.selectAccount(id);
    }
  };
  $scope.refreshAccounts = function() {
    return dataSource.getAccounts().then(function(accounts) {
      var account, foundSelected, _i, _len;

      $scope.accounts = accounts;
      foundSelected = false;
      for (_i = 0, _len = accounts.length; _i < _len; _i++) {
        account = accounts[_i];
        if (account._id === $scope.selectedAccountId) {
          $rootScope.$broadcast('accountChanged', $scope.selectedAccountId);
          foundSelected = true;
        }
      }
      if (!foundSelected && accounts.length > 0) {
        $scope.selectedAccountId = accounts[accounts.length - 1]._id;
        localStorage['cashflow_selectedAccountId'] = $scope.selectedAccountId;
        $rootScope.$broadcast('accountChanged', $scope.selectedAccountId);
      }
      return $scope.refreshTotal();
    });
  };
  $rootScope.$on('accountChanged', function(event, id) {
    return $scope.accounts.forEach(function(account) {
      return account.selected = account._id === id;
    });
  });
  $rootScope.$on('dataSourceReady', function(event, id) {
    return $scope.refreshAccounts();
  });
  $scope.refreshTotal = function() {
    return dataSource.getItems($scope.selectedAccountId).then(function(items) {
      var account, sum, _i, _len, _ref, _results;

      items.sort(function(a, b) {
        return a.date.getTime() - b.date.getTime();
      });
      sum = 0;
      items.forEach(function(item) {
        if (item.operation === '=') {
          sum = item.value;
        }
        if (item.operation === '-') {
          sum -= item.value;
        }
        if (item.operation === '+') {
          sum += item.value;
        }
        if (item.operation === '<') {
          sum -= item.value;
        }
        if (item.operation === '>') {
          return sum += item.value;
        }
      });
      sum = '' + Math.floor(sum * 100) / 100;
      if (sum.indexOf('.') === -1) {
        sum = sum + '.00';
      }
      if (sum.indexOf('.') === sum.length - 2) {
        sum = sum + '0';
      }
      _ref = $scope.accounts;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        account = _ref[_i];
        if (account._id === $scope.selectedAccountId) {
          _results.push(account.value = sum + ' / ' + items.length);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  };
  return $rootScope.$on('itemChanged', function(event, item) {
    return $scope.refreshTotal();
  });
};
