// Generated by CoffeeScript 1.6.2
cashflow.controller('ItemFormController', function($timeout, $rootScope, $scope, $q, dataSource) {
  $scope.mode = '';
  $scope.updating = '';
  $rootScope.$on('accountChanged', function(event, id) {
    return $scope.accountid = id;
  });
  $scope.onAddButtonClick = function() {
    if ($scope.mode === '') {
      $scope.date = dataSource.dateToIso(new Date());
      $scope.operation = '-';
      $scope.value = '';
      $scope.value2 = '';
      $scope.category = '';
      $scope.notes = '';
      $scope.recurring = '';
      return $scope.mode = 'add';
    } else if ($scope.mode === 'add') {
      $scope.updating = 'adding';
      $scope.mode = '';
      return dataSource.addItem($scope.accountid, $scope.date, $scope.operation, $scope.value, $scope.value2, $scope.category, $scope.notes, $scope.recurring).then(function() {
        return $scope.updating = '';
      });
    } else if ($scope.mode === 'pay') {
      $scope.updating = 'adding';
      $scope.mode = '';
      $scope.editedItem.parentItem.recurring = '';
      dataSource.updateItem($scope.editedItem.parentItem);
      return dataSource.addItem($scope.accountid, $scope.date, $scope.operation, $scope.value, $scope.value2, $scope.category, $scope.notes, $scope.recurring).then(function() {
        return $scope.updating = '';
      });
    } else if ($scope.mode === 'edit') {
      $scope.updating = 'editing';
      $scope.mode = '';
      return dataSource.updateItem($scope.editedItem, $scope.accountid, $scope.date, $scope.operation, $scope.value, $scope.value2, $scope.category, $scope.notes, $scope.recurring).then(function() {
        return $scope.updating = '';
      });
    }
  };
  $rootScope.$on('editItem', function(event, item) {
    if ($scope.mode === '') {
      $scope.editedItem = item;
      $scope.accountid = item.accountid;
      $scope.date = dataSource.dateToIso(item.date);
      $scope.operation = item.operation;
      $scope.value = Math.floor(item.value);
      $scope.value2 = Math.floor((item.value - Math.floor(item.value)) * 100);
      $scope.category = item.category;
      $scope.notes = item.notes;
      $scope.recurring = item.recurring;
      return $scope.mode = 'edit';
    }
  });
  $rootScope.$on('payItem', function(event, item) {
    if ($scope.mode === '') {
      $scope.editedItem = item;
      $scope.accountid = item.accountid;
      $scope.date = dataSource.dateToIso(item.date);
      $scope.operation = item.operation;
      $scope.value = Math.floor(item.value);
      $scope.value2 = Math.floor((item.value - Math.floor(item.value)) * 100);
      $scope.category = item.category;
      $scope.notes = item.notes;
      $scope.recurring = item.recurring;
      return $scope.mode = 'pay';
    }
  });
  return $scope.onCancelButtonClick = function() {
    if ($scope.mode !== '') {
      return $scope.mode = '';
    }
  };
});
