// Generated by CoffeeScript 1.6.2
cashflow.controller('MenuController', function($rootScope, $scope, $q, dataSource) {
  $scope.settingsVisible = false;
  $scope.syncState = 'sync';
  $scope.lastUpdated = localStorage['cashflow_lastUpdated'] ? new Date(localStorage['cashflow_lastUpdated']) : 'never';
  $scope.toggleSettings = function() {
    return $scope.settingsVisible = !$scope.settingsVisible;
  };
  $scope.toggleMonthlySummary = function() {
    return $rootScope.$broadcast('toggleMonthlySummary');
  };
  $scope.sync = function() {
    $scope.syncOut(true);
    return $scope.syncIn(true);
  };
  $scope.syncOut = function(continuous) {
    $scope.syncState = 'syncing... out';
    console.log('MenuController: replicating out');
    return Pouch.replicate('cashflow', 'http://node.variable.io:5984/cashflow', {
      continuous: continuous,
      onChange: function(change) {
        return console.log('MenuController: change out', change);
      },
      complete: function(change) {
        return console.log('MenuController: change out complete', change);
      }
    }, function(err, changes) {
      console.log('MenuController: replication out finished', err, changes);
      if (!continuous) {
        return $scope.syncIn(false);
      }
    });
  };
  return $scope.syncIn = function(continuous) {
    if (!continuous) {
      $rootScope.$apply(function() {
        return $scope.syncState = 'syncing... in';
      });
    } else {
      $scope.syncState = 'syncing... in';
    }
    console.log('MenuController: replicating in');
    return Pouch.replicate('http://node.variable.io:5984/cashflow', 'cashflow', {
      continuous: continuous,
      onChange: function(change) {
        return console.log('MenuController: change in', change);
      },
      complete: function(change) {
        return console.log('MenuController: change in complete', change);
      }
    }, function(err, changes) {
      console.log('MenuController: replication in finished', err, changes);
      if (!continuous) {
        return $rootScope.$apply(function() {
          $scope.syncState = 'sync';
          localStorage['cashflow_lastUpdated'] = '' + new Date();
          return $scope.lastUpdated = new Date(localStorage['cashflow_lastUpdated']);
        });
      }
    });
  };
});
